server:
  servlet:
    context-path: /api

spring:
  application:
    name: Misaki
  profiles:
      active: prod
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  web:
    locale: en_US
    locale-resolver: fixed

  jackson:
    time-zone: Asia/Shanghai
    locale: zh

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 600000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: hikariCP
    url: ${misaki.mysql.url}
    username: ${misaki.mysql.username}
    password: ${misaki.mysql.password}

  mail:
    host: smtp.qq.com
    port: 465
    username: ${misaki.mail.username}
    password: ${misaki.mail.password}
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  data:
    redis:
      host: ${misaki.redis.host}
      port: ${misaki.redis.port}
      database: 0

  ai:
    deepseek:
      base-url: ${misaki.ai.base-url}
      api-key: ${misaki.ai.api-key}
      chat:
        options:
          model: deepseek-chat
          temperature: 0.8

    mcp:
      client:
        stdio:
          connections:
            time:
              command: docker
              args:
                - run
                - -i
                - --rm
                - mcp/time
            fetch:
              command: docker
              args:
                - run
                - -i
                - --rm
                - mcp/fetch
            duckduckgo:
              command: docker
              args:
                - run
                - -i
                - --rm
                - mcp/duckduckgo
            wikipedia:
              command: docker
              args:
                - run
                - -i
                - --rm
                - mcp/wikipedia-mcp
            # context7:
            #   command: docker
            #   args:
            #     - run
            #     - -i
            #     - --rm
            #     - mcp/context7

springdoc:
  api-docs:
    version: OPENAPI_3_0

management:
  metrics:
    enable:
      all: false
      http: true
  endpoints:
    web:
      exposure:
        include: health, metrics

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    banner: false

minio:
  endpoint: ${misaki.minio.endpoint}
  access-key: ${misaki.minio.access-key}
  secret-key: ${misaki.minio.secret-key}
  bucket: ${misaki.minio.bucket}

misaki:
  jwt:
    secret: kotoshi_nakahara_misaki_wa_kitto_kuru
    expiration: 86400000
  request:
    expiration: 60000
  business:
    auth:
      max-password-retry-count: 5
      password-retry-time-window: 5
    user:
      check-in:
        token: 10000
        crystal: 60
      delete:
        cooldown-days: 7
    wish:
      exchange-rate:
        puzzle-crystal: 160
        puzzle-stardust: 75
      compensation:
        four-star: 50
        five-star: 100
      token:
        limit: 10000
      probability:
        four-star: 0.050
        five-star: 0.006
