server:
  servlet:
    context-path: /api
  port: 8080
spring:
  application:
    name: Misaki
  servlet:
    multipart:
      max-file-size: 10MB       # 单个文件最大 10MB
      max-request-size: 20MB    # 单次请求总大小（多个文件加起来）
  web:
    locale: en_US
    locale-resolver: fixed
  jackson:
    time-zone: Asia/Shanghai
    locale: zh
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 600000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: hikariCP
    url: ${misaki.mysql.url}
    username: ${misaki.mysql.username}
    password: ${misaki.mysql.password}
  mail:
    host: smtp.qq.com
    port: 465
    username: ${misaki.mail.username}
    password: ${misaki.mail.password}
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  data:
    redis:
      host: ${misaki.redis.host}
      port: ${misaki.redis.port}
      database: 0
  ai:
    deepseek:
      base-url: ${misaki.ai.base-url}
      api-key: ${misaki.ai.api-key}
      chat:
        options:
          model: deepseek-chat
          temperature: 0.8
    mcp:
      client:
        name: misaki-mcp-client
        version: 1.0.0
        type: async
        sse:
          connections:
            server1:
              url: http://localhost:8080
        enabled: false

springdoc:
  api-docs:
    version: OPENAPI_3_0

management:
  metrics:
    enable:
      all: false
      http: true
  endpoints:
    web:
      exposure:
        include: health, metrics

#logging:
#  level:
#    org.springframework.web: DEBUG

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    banner: false
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  endpoint: ${misaki.minio.endpoint}
  access-key: ${misaki.minio.access-key}
  secret-key: ${misaki.minio.secret-key}
  bucket: ${misaki.minio.bucket}

misaki:
  jwt:
    secret: kotoshi_nakahara_misaki_wa_kitto_kuru
    expiration: 7200000
  mysql:
    url: jdbc:mysql://localhost:3306/misaki?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin
  redis:
    host: localhost
    port: 6379
  mail:
    username: kiyomizu_wx@qq.com
    password: yexqazyxodclecdg
  ai:
    base-url: https://api.deepseek.com
    api-key: sk-c846b63a4b544b248b414725883123b2
  minio:
    endpoint: http://localhost:9000
    access-key: misaki
    secret-key: nakahara
    bucket: misaki
  business:
    auth:
      max-password-retry-count: 5
      password-retry-time-window: 5  #分钟
    user:
      check-in:
        token: 10000
        crystal: 60
      delete:
        cooldown-days: 7
    wish:
      exchange-rate:
        puzzle-crystal: 160
        puzzle-stardust: 20
      compensation:
        four-star: 50
        five-star: 100
      token:
        limit: 10000
      probability:
        base: 1000
        token: 900
        four-star: 994