server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

misaki:
  mysql:
    url: jdbc:mysql://localhost:3306/misaki?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin

  redis:
    host: localhost
    port: 6379

  mail:
    username: kiyomizu_wx@qq.com
    password: yexqazyxodclecdg

  ai:
    base-url: https://api.deepseek.com
    api-key: sk-c846b63a4b544b248b414725883123b2

  minio:
    endpoint: http://localhost:9000
    access-key: misaki
    secret-key: nakahara
    bucket: misaki
